/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables.records;


import com.duoduo.schema.tables.Order;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record11<Long, String, String, Timestamp, String, String, String, String, Timestamp, String, String> {

    private static final long serialVersionUID = 1893058744;

    /**
     * Setter for <code>duoduo.order.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>duoduo.order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>duoduo.order.task_id</code>.
     */
    public void setTaskId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>duoduo.order.task_id</code>.
     */
    public String getTaskId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>duoduo.order.order_json</code>.
     */
    public void setOrderJson(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>duoduo.order.order_json</code>.
     */
    public String getOrderJson() {
        return (String) get(2);
    }

    /**
     * Setter for <code>duoduo.order.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>duoduo.order.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>duoduo.order.order_id</code>.
     */
    public void setOrderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>duoduo.order.order_id</code>.
     */
    public String getOrderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>duoduo.order.mobile</code>.
     */
    public void setMobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>duoduo.order.mobile</code>.
     */
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>duoduo.order.content</code>.
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>duoduo.order.content</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>duoduo.order.receive_message_json</code>.
     */
    public void setReceiveMessageJson(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>duoduo.order.receive_message_json</code>.
     */
    public String getReceiveMessageJson() {
        return (String) get(7);
    }

    /**
     * Setter for <code>duoduo.order.receive_time</code>.
     */
    public void setReceiveTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>duoduo.order.receive_time</code>.
     */
    public Timestamp getReceiveTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>duoduo.order.send_message_json</code>.
     */
    public void setSendMessageJson(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>duoduo.order.send_message_json</code>.
     */
    public String getSendMessageJson() {
        return (String) get(9);
    }

    /**
     * Setter for <code>duoduo.order.receive_content</code>.
     */
    public void setReceiveContent(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>duoduo.order.receive_content</code>.
     */
    public String getReceiveContent() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Timestamp, String, String, String, String, Timestamp, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, Timestamp, String, String, String, String, Timestamp, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Order.ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Order.ORDER.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Order.ORDER.ORDER_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Order.ORDER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Order.ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Order.ORDER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Order.ORDER.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Order.ORDER.RECEIVE_MESSAGE_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Order.ORDER.RECEIVE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Order.ORDER.SEND_MESSAGE_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Order.ORDER.RECEIVE_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrderJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getReceiveMessageJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getReceiveTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSendMessageJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getReceiveContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value2(String value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value3(String value) {
        setOrderJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value5(String value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value6(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value7(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value8(String value) {
        setReceiveMessageJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value9(Timestamp value) {
        setReceiveTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value10(String value) {
        setSendMessageJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord value11(String value) {
        setReceiveContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderRecord values(Long value1, String value2, String value3, Timestamp value4, String value5, String value6, String value7, String value8, Timestamp value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Long id, String taskId, String orderJson, Timestamp createTime, String orderId, String mobile, String content, String receiveMessageJson, Timestamp receiveTime, String sendMessageJson, String receiveContent) {
        super(Order.ORDER);

        set(0, id);
        set(1, taskId);
        set(2, orderJson);
        set(3, createTime);
        set(4, orderId);
        set(5, mobile);
        set(6, content);
        set(7, receiveMessageJson);
        set(8, receiveTime);
        set(9, sendMessageJson);
        set(10, receiveContent);
    }
}
