/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema.tables.records;


import com.duoduo.schema.tables.ReceiveMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiveMessageRecord extends UpdatableRecordImpl<ReceiveMessageRecord> implements Record3<Long, String, Timestamp> {

    private static final long serialVersionUID = -3151657;

    /**
     * Setter for <code>duoduo.receive_message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>duoduo.receive_message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>duoduo.receive_message.receive_message_json</code>.
     */
    public void setReceiveMessageJson(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>duoduo.receive_message.receive_message_json</code>.
     */
    public String getReceiveMessageJson() {
        return (String) get(1);
    }

    /**
     * Setter for <code>duoduo.receive_message.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>duoduo.receive_message.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ReceiveMessage.RECEIVE_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ReceiveMessage.RECEIVE_MESSAGE.RECEIVE_MESSAGE_JSON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ReceiveMessage.RECEIVE_MESSAGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReceiveMessageJson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceiveMessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceiveMessageRecord value2(String value) {
        setReceiveMessageJson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceiveMessageRecord value3(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceiveMessageRecord values(Long value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceiveMessageRecord
     */
    public ReceiveMessageRecord() {
        super(ReceiveMessage.RECEIVE_MESSAGE);
    }

    /**
     * Create a detached, initialised ReceiveMessageRecord
     */
    public ReceiveMessageRecord(Long id, String receiveMessageJson, Timestamp createTime) {
        super(ReceiveMessage.RECEIVE_MESSAGE);

        set(0, id);
        set(1, receiveMessageJson);
        set(2, createTime);
    }
}
