/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema;


import com.duoduo.schema.tables.Configuration;
import com.duoduo.schema.tables.Order;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Duoduo extends SchemaImpl {

    private static final long serialVersionUID = 749199621;

    /**
     * The reference instance of <code>duoduo</code>
     */
    public static final Duoduo DUODUO = new Duoduo();

    /**
     * The table <code>duoduo.configuration</code>.
     */
    public final Configuration CONFIGURATION = com.duoduo.schema.tables.Configuration.CONFIGURATION;

    /**
     * The table <code>duoduo.order</code>.
     */
    public final Order ORDER = com.duoduo.schema.tables.Order.ORDER;

    /**
     * No further instances allowed
     */
    private Duoduo() {
        super("duoduo", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Configuration.CONFIGURATION,
            Order.ORDER);
    }
}
