/**
 * This class is generated by jOOQ
 */
package com.duoduo.schema;


import com.duoduo.schema.tables.Configuration;
import com.duoduo.schema.tables.Order;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in duoduo
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>duoduo.configuration</code>.
     */
    public static final Configuration CONFIGURATION = com.duoduo.schema.tables.Configuration.CONFIGURATION;

    /**
     * The table <code>duoduo.order</code>.
     */
    public static final Order ORDER = com.duoduo.schema.tables.Order.ORDER;
}
